### ISSUE TITLE
Doesn't pick up requirements with different import names

### ISSUE THREAD

**Issue by Dreamsorcerer** [Arkq/flake8-requirements#23]
Maybe a bit of an edge case, but when the PyPI name is different from the import name, this fails to pick it up automatically.

Example is:
`pip install PyGObject`
which is imported with:
`import gi`
and results in:
`I900 'gi' not listed as a requirement`
even when `PyGObject` is added to the requirements file.

Maybe a solution would be to check through the installed packages something like this:
```
from pip._internal.utils.misc import get_installed_distributions

module_map = {module: dist.project_name for dist in get_installed_distributions() for module in dist._get_metadata("top_level.txt")}
import_name = "gi"
project_name = module_map.get(import_name, import_name)  # -> "PyGObject"
```

**Comment by Arkq** [comment]
If module name and import name are different, there is a requirement to add 3rd party mapping: https://github.com/Arkq/flake8-requirements/blob/master/src/flake8_requirements/modules.py#L503

Since, there is a lot of 3rd party modules sometimes it is easier to add them locally via custom mappings: https://github.com/Arkq/flake8-requirements#customization The [modules.py](https://github.com/Arkq/flake8-requirements/blob/master/src/flake8_requirements/modules.py#L503) is only for "well-known" 3rd party modules.

> Maybe a solution would be to check through the installed packages something like this:

No, it's not a solution, because one should be able to run linter (flake8 in this case) in an "offline" mode - without installing all requirements. After all this flake8 checker is for checking whether all used modules are listed in the setup.py (or requirements.txt) file - it would be impossible to install module if it is not listed. Imagine, that you lint your code on a dedicated continuous-integration server which lints many projects. It would not be feasible to install every newly used python module on such CI server.

**Comment by Dreamsorcerer** [comment]
Yep, I figured there were issues, but made sure that it still falls back to the existing behaviour if not installed.

If there's already a solution though, I'll make a PR for that instead.
